### ISSUE TITLE
Csv.toCsv - work with Seq[TimeSeries[A]] 

### ISSUE THREAD

**Issue by wenta** [carldata/timeseries#118]
-maybe create `toComplexCsv[A](xs:Seq[TimeSeries[A]] ) : String` next to `toCsv[A](xs: TimeSeries[A]): String`

**Comment by alexander-myltsev** [comment]
What's the output of the function should look like? WDYT if output of `toComplexCsv(Seq(ts1, ts2, ts3))` would be new-line separated values as follows:

```
time,value
2005-01-01T12:34:15,2
2006-01-01T12:34:15,-4
2007-01-01T12:34:15,-6
2008-01-01T12:34:15,9

time,value
2005-01-01T12:34:15,2
2008-01-01T12:34:15,9

time,value
2005-01-01T12:34:15,2
2006-01-01T12:34:15,-4
2007-01-01T12:34:15,-6
```

**Comment by wenta** [comment]
Hi, thanks for your message. We want to create here function opposite to ```fromString(str: String, dateFormatter: DateTimeFormatter = defaultFormatter): Seq[TimeSeries[Double]]``` .  ```toComplexCsv``` should create csv format readable by ```fromString```, so example output should be following: 
``` csv
time,value
2005-01-01T12:34:15,2,3,1
2006-01-01T12:34:15,-4,-1,1
2007-01-01T12:34:15,-6,0,0
2008-01-01T12:34:15,9,2,1
```
In this task we need to figure out what about situation when time series in sequence have different index. (For example we can force to join them).

**Comment by alexander-myltsev** [comment]
WDYT of leaving empty string for the value missing in the index?

```
time,value
2005-01-01T12:34:15,2,3,1
2006-01-01T12:34:25,,-1,1
2007-01-01T12:34:35,-6,,0
2008-01-01T12:34:45,9,,
```

**Comment by wenta** [comment]
I think this is Ok, but we cannot implement it yet because `fromString` fail on this csv, so we should update it first.
Secondly it will be better if this output string will be readable by others library too. I tried to load it via pandas and I got exception. Pandas handle empty value (put `Nan`) but fail because length of the header do not correspond to length of next rows. We could change header to `time,value1,value2,`etc..

**Comment by alexander-myltsev** [comment]
OK.

What amount of values do you estimate (i.e. size of xs)? Do you think continuously calling `joinOuter` for times equal to amount of values would be bearable? Otherwise `join`s should be extended to handle multiple `TimeSeries`-es in a row.

**Comment by wenta** [comment]
I think we can start here with current join, and later update it if it performance will be not ok. 

> Make it run, Make it right, Make it fast
