### ISSUE TITLE
2.11 release

### ISSUE THREAD

**Issue by xdev-developer** [carldata/timeseries#121]
Hi, thanks for the library.
It is possible release this library for scala 2.11?

**Comment by wenta** [comment]
I will look at it and let you know.

**Comment by wenta** [comment]
Hi, new release you can find at https://mvnrepository.com/artifact/io.github.carldata/timeseries_2.11/0.6.7
If you like give a star to project, have a nice day.

**Comment by test-to-exist** [comment]
Yea, please let us know if it actually works ;-)

**Comment by xdev-developer** [comment]
Yes, it works!!!
Thank you! And this is really nice library!
