### ISSUE TITLE
New functions proposal

### ISSUE THREAD

**Issue by alexander-myltsev** [carldata/timeseries#122]
I'm looking for a lib to process time series. You did a lot of work and miles ahead of what I've found.

I'd like to use your lib in the financial data domain. For starters, common tasks are:
- check if data is continuous with respect to the `period frequency`. For example, if the period frequency is the month, then I need to check if there is at least one data point per month 
- fill gaps according to some predefined policies: take the previous non-null, take next one non-null, fill with linear space between previous and next
- more advanced filtering. I'd like to extract data points that are last in the current month
- having two or more series with different time series, I'd like to fill missing values according to some policy that unifies time series, so I can make algebraic operations on them

Do you think it is in the scope of the library? If yes, I'd like to discuss the details and make a contribution.

**Comment by alexander-myltsev** [comment]
Also, what does the library propose to do regular operations like addition and multiplication on time series? Is it only `map` over `zip`ped series, or are there overloads?

**Comment by wenta** [comment]
Hi, Yes I think that it will be nice to add more functions to library. We already have some basic operations on time series, and I want to keep them as a core. It will be good to group new methods by their applications. 
> Also, what does the library propose to do regular operations like addition and multiplication on time series? Is it only map over zipped series, or are there overloads?

Addition is very easy to make with a map, so we didn't include them into TimeSeries class. 
We could create module ```carldata.extras.MathModule```, with implicit class :
```scala
object MathModule {

  implicit class TimeSeriesMathOperations[V](ts: TimeSeries[V]) {
    def add(v: V)(implicit num: Numeric[V]): TimeSeries[V] = ts.mapValues(x => num.plus(x, v))
  }

}
```
Advanced filtering and filling missing points should go to separate modules too.
  
> having two or more series with different time series, I'd like to fill missing values according to some policy that unifies time series, so I can make algebraic operations on them

Take a look at `TimeSeries.joinOuter`
Summarizing, feel free to open new issues and PR, You are welcome :)

**Comment by alexander-myltsev** [comment]
> Addition is very easy to make with a map, so we didn't include them into TimeSeries class.
We could create module carldata.extras.MathModule, with implicit class :

What do you think of exact arithmetic operations like `+` and `*` exactly on timeseries instances?

```
val t: TimeSeries = // ...
val r = t + t * t
```

I suppose the exception should be thrown in case of misaligned index? 

> Take a look at TimeSeries.joinOuter

Got that! Thanks!


Do you think `Vector` type for indices is effective enough? What do you think of using Breeze for the backend representation?


Also, what do you think on cross-building against Dotty?

**Comment by wenta** [comment]
> ```val r = t + t * t```

Yes, we could create this syntax sugar :) I don't like throwing exception, better return empty result or as Option or Either.
Introduce Breeze here will be copernican revolution and I would like to avoid it, there is a lot of relationships in other projects and libs.
Dotty is a future of Scala, it is a natural path to support it. But it is still under active development, I would like to wait with introduce it to this library for a while.

**Comment by alexander-myltsev** [comment]
Could the lib at least abstract over representation of values? I might want one day to compute the result, say, closer to metal (C/C++ or GPU).

**Comment by wenta** [comment]
What do you mean by abstract? Values are already `Numeric` so we allow a certain range of types.

**Comment by alexander-myltsev** [comment]
I meant that one: https://github.com/carldata/timeseries/blob/master/shared/src/main/scala/carldata/series/TimeSeries.scala#L178 

`Vector` is concrete type. What if it would be Breeze vector, or some gpu Vector? I suggest you to extract it to some `VectorLike` interface, someday. For now `Vector` seems fine.
