### ISSUE TITLE
Custom index

### ISSUE THREAD

**Issue by alexander-myltsev** [carldata/timeseries#127]
I’d like to work with complex indices types. Use cases are as follows:
- pandas analogue to period with freq=’M’ when there is only year and month. And for some series the period relates to first day of month, and for some to last day of month. And I’d like those series to be incompatible by index 
- I have activities that requires time series to be reduced. Say, I have data from 2015-5 to 2017-7. Then I need to get a YTD reduction that is a function for data for 3 period ranges: [2015-5, 2015-12], [2016-1, 2016-12], [2017-1, 2017-7]. I.e. the index is period range. There are cases when time series with incomplete period ranges are compatible, and other cases when are not

Are custom indices in the scope of the library?

**Comment by wenta** [comment]
I think this is too detailed application and I would like to maintain this library a little more general.

**Comment by alexander-myltsev** [comment]
I'm not sure what do you mean by "general". I thought I proposed more general type for index, and current implementation would be one of specialisations. 

But OK. Alas, I can't use the library with current approach for indices.
