### ISSUE TITLE
New repeat function

### ISSUE THREAD

**Issue by wenta** [carldata/timeseries#77]
```
def repeat(start: Instant, end: Instant, repetitionStart: Instant, repetitionEnd: Instant): TimeSeries[V]

**Comment by klangner** [comment]
Could you add this function to the generators?

And I would suggest to change the signature to:
```
def repeat(pattern: TimeSeries[V], start: Instant, end: Instant): TimeSeries[V] 
```

This function will create new series form **start** to **end** by repeating pattern as many times as needed.

We can use slice on time series to select pattern

**Comment by wenta** [comment]
Yes, I agree, and in test of this function I will use this slice to show example usage.
